print(type(4))
print(type(4.0))
print(type("Hello"))
print(type(True))
print(type([1, 2, 3]))
print(type((1, 2, 3)))
print(type({1, 2, 3}))
print(type({"name": "Alice", "age": 30}))
print(type(None))
print(type(lambda x: x + 1))
print(type(range(5)))
print(type(bytearray(b"Hello")))
print(type(bytes(b"Hello")))
print(type(memoryview(b"Hello")))
print(type(complex(1, 2)))
print(type(frozenset([1, 2, 3])))
print(type(object()))
print(type(NotImplemented))
print(type(Ellipsis))
print(type(slice(1, 5)))
print(type(type(4)))
print(type(Exception("Error")))
print(type(StopIteration()))
print(type(KeyboardInterrupt()))
print(type(SystemExit()))
print(type(GeneratorExit()))
print(type(Warning("Warning")))
print(type(DeprecationWarning("Deprecation Warning")))
print(type(ImportWarning("Import Warning")))
print(type(PendingDeprecationWarning("Pending Deprecation Warning")))
print(type(RuntimeWarning("Runtime Warning")))
print(type(SyntaxWarning("Syntax Warning")))
print(type(UserWarning("User Warning")))
print(type(FutureWarning("Future Warning")))
print(type(ResourceWarning("Resource Warning")))
print(type(BaseException("Base Exception")))
print(type(ArithmeticError("Arithmetic Error")))
print(type(AssertionError("Assertion Error")))
print(type(AttributeError("Attribute Error")))
print(type(BufferError("Buffer Error")))